server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
  # 平滑关闭
  shutdown: graceful

spring:
  profiles:
    active: dev

  messages:
    encoding: utf-8

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true
  config:
    import: classpath:admin.yml
  application:
    name: "@artifactId@"

mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: io.webapp.*.entity

  # xml 扫描路径
  mapper-locations: classpath:mapper/*/*.xml

  configuration:
    jdbc-type-for-null: null

  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false
    db-config:
      select-strategy: not_empty

# 数据脱敏
logging:
  level:
    com:
      baomidou:
        mybatisplus:
          core:
            metadata:
              TableInfoHelper: error
